import { OnInit, ElementRef, EventEmitter, AfterViewInit, SimpleChanges, OnChanges } from '@angular/core';
import { Map } from 'ol';
import MapBrowserEvent from 'ol/MapBrowserEvent';
import MapEvent from 'ol/MapEvent';
import { ObjectEvent } from 'ol/Object';
import RenderEvent from 'ol/render/Event';
import { Control } from 'ol/control';
import { Interaction } from 'ol/interaction';
import { DrawEvent } from 'ol/interaction/Draw';
import BaseEvent from 'ol/events/Event';
import * as i0 from "@angular/core";
export declare class MapComponent implements OnInit, AfterViewInit, OnChanges {
    private host;
    width: string;
    height: string;
    pixelRatio: number;
    keyboardEventTarget: HTMLElement | string;
    loadTilesWhileAnimating: boolean;
    loadTilesWhileInteracting: boolean;
    logo: string | boolean;
    renderer: 'canvas' | 'webgl';
    olChange: EventEmitter<DrawEvent>;
    olChangeLayerGroup: EventEmitter<ObjectEvent>;
    olChangeSize: EventEmitter<ObjectEvent>;
    olChangeTarget: EventEmitter<ObjectEvent>;
    olChangeView: EventEmitter<ObjectEvent>;
    olClick: EventEmitter<MapBrowserEvent<MouseEvent>>;
    dblClick: EventEmitter<MapBrowserEvent<MouseEvent>>;
    olError: EventEmitter<BaseEvent>;
    loadEnd: EventEmitter<MapEvent>;
    loadStart: EventEmitter<MapEvent>;
    moveEnd: EventEmitter<MapEvent>;
    moveStart: EventEmitter<MapEvent>;
    pointerDrag: EventEmitter<MapBrowserEvent<MouseEvent>>;
    pointerMove: EventEmitter<MapBrowserEvent<MouseEvent>>;
    olPostCompose: EventEmitter<RenderEvent>;
    olPostRender: EventEmitter<RenderEvent>;
    olPreCompose: EventEmitter<RenderEvent>;
    olPropertyChange: EventEmitter<ObjectEvent>;
    postRender: EventEmitter<MapEvent>;
    propertyChange: EventEmitter<ObjectEvent>;
    singleClick: EventEmitter<MapBrowserEvent<MouseEvent>>;
    instance: Map;
    componentType: string;
    controls: Control[];
    interactions: Interaction[];
    constructor(host: ElementRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngAfterViewInit(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<MapComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<MapComponent, "aol-map", never, { "width": { "alias": "width"; "required": false; }; "height": { "alias": "height"; "required": false; }; "pixelRatio": { "alias": "pixelRatio"; "required": false; }; "keyboardEventTarget": { "alias": "keyboardEventTarget"; "required": false; }; "loadTilesWhileAnimating": { "alias": "loadTilesWhileAnimating"; "required": false; }; "loadTilesWhileInteracting": { "alias": "loadTilesWhileInteracting"; "required": false; }; "logo": { "alias": "logo"; "required": false; }; "renderer": { "alias": "renderer"; "required": false; }; }, { "olChange": "olChange"; "olChangeLayerGroup": "olChangeLayerGroup"; "olChangeSize": "olChangeSize"; "olChangeTarget": "olChangeTarget"; "olChangeView": "olChangeView"; "olClick": "olClick"; "dblClick": "dblClick"; "olError": "olError"; "loadEnd": "loadEnd"; "loadStart": "loadStart"; "moveEnd": "moveEnd"; "moveStart": "moveStart"; "pointerDrag": "pointerDrag"; "pointerMove": "pointerMove"; "olPostCompose": "olPostCompose"; "olPostRender": "olPostRender"; "olPreCompose": "olPreCompose"; "olPropertyChange": "olPropertyChange"; "postRender": "postRender"; "propertyChange": "propertyChange"; "singleClick": "singleClick"; }, never, ["*"], false, never>;
}
//# sourceMappingURL=map.component.d.ts.map